// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: resource_usage_agent.proto

package resource_usage_agent

import (
	"fmt"
	"io"
	"math"

	proto "github.com/golang/protobuf/proto"

	_ "github.com/gogo/protobuf/gogoproto"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CPUTimeRecord struct {
	ResourceGroupTag []byte `protobuf:"bytes,1,opt,name=resource_group_tag,json=resourceGroupTag,proto3" json:"resource_group_tag,omitempty"`
	// UNIX timestamp in second.
	RecordListTimestampSec []uint64 `protobuf:"varint,2,rep,packed,name=record_list_timestamp_sec,json=recordListTimestampSec" json:"record_list_timestamp_sec,omitempty"`
	// The value can be greater than 1000ms if the requests are running parallelly.
	RecordListCpuTimeMs  []uint32 `protobuf:"varint,3,rep,packed,name=record_list_cpu_time_ms,json=recordListCpuTimeMs" json:"record_list_cpu_time_ms,omitempty"`
	RecordListScanRows   []uint64 `protobuf:"varint,4,rep,packed,name=record_list_scan_rows,json=recordListScanRows" json:"record_list_scan_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPUTimeRecord) Reset()         { *m = CPUTimeRecord{} }
func (m *CPUTimeRecord) String() string { return proto.CompactTextString(m) }
func (*CPUTimeRecord) ProtoMessage()    {}
func (*CPUTimeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_usage_agent_9193562f1798a3b8, []int{0}
}
func (m *CPUTimeRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CPUTimeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CPUTimeRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CPUTimeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUTimeRecord.Merge(dst, src)
}
func (m *CPUTimeRecord) XXX_Size() int {
	return m.Size()
}
func (m *CPUTimeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUTimeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_CPUTimeRecord proto.InternalMessageInfo

func (m *CPUTimeRecord) GetResourceGroupTag() []byte {
	if m != nil {
		return m.ResourceGroupTag
	}
	return nil
}

func (m *CPUTimeRecord) GetRecordListTimestampSec() []uint64 {
	if m != nil {
		return m.RecordListTimestampSec
	}
	return nil
}

func (m *CPUTimeRecord) GetRecordListCpuTimeMs() []uint32 {
	if m != nil {
		return m.RecordListCpuTimeMs
	}
	return nil
}

func (m *CPUTimeRecord) GetRecordListScanRows() []uint64 {
	if m != nil {
		return m.RecordListScanRows
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_usage_agent_9193562f1798a3b8, []int{1}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return m.Size()
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CPUTimeRecord)(nil), "resource_usage_agent.CPUTimeRecord")
	proto.RegisterType((*EmptyResponse)(nil), "resource_usage_agent.EmptyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ResourceUsageAgent service

type ResourceUsageAgentClient interface {
	// Report the CPU time records. By default, the records with the same
	// resource group tag will be batched by minute.
	ReportCPUTime(ctx context.Context, opts ...grpc.CallOption) (ResourceUsageAgent_ReportCPUTimeClient, error)
}

type resourceUsageAgentClient struct {
	cc *grpc.ClientConn
}

func NewResourceUsageAgentClient(cc *grpc.ClientConn) ResourceUsageAgentClient {
	return &resourceUsageAgentClient{cc}
}

func (c *resourceUsageAgentClient) ReportCPUTime(ctx context.Context, opts ...grpc.CallOption) (ResourceUsageAgent_ReportCPUTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceUsageAgent_serviceDesc.Streams[0], "/resource_usage_agent.ResourceUsageAgent/ReportCPUTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceUsageAgentReportCPUTimeClient{stream}
	return x, nil
}

type ResourceUsageAgent_ReportCPUTimeClient interface {
	Send(*CPUTimeRecord) error
	CloseAndRecv() (*EmptyResponse, error)
	grpc.ClientStream
}

type resourceUsageAgentReportCPUTimeClient struct {
	grpc.ClientStream
}

func (x *resourceUsageAgentReportCPUTimeClient) Send(m *CPUTimeRecord) error {
	return x.ClientStream.SendMsg(m)
}

func (x *resourceUsageAgentReportCPUTimeClient) CloseAndRecv() (*EmptyResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EmptyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ResourceUsageAgent service

type ResourceUsageAgentServer interface {
	// Report the CPU time records. By default, the records with the same
	// resource group tag will be batched by minute.
	ReportCPUTime(ResourceUsageAgent_ReportCPUTimeServer) error
}

func RegisterResourceUsageAgentServer(s *grpc.Server, srv ResourceUsageAgentServer) {
	s.RegisterService(&_ResourceUsageAgent_serviceDesc, srv)
}

func _ResourceUsageAgent_ReportCPUTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceUsageAgentServer).ReportCPUTime(&resourceUsageAgentReportCPUTimeServer{stream})
}

type ResourceUsageAgent_ReportCPUTimeServer interface {
	SendAndClose(*EmptyResponse) error
	Recv() (*CPUTimeRecord, error)
	grpc.ServerStream
}

type resourceUsageAgentReportCPUTimeServer struct {
	grpc.ServerStream
}

func (x *resourceUsageAgentReportCPUTimeServer) SendAndClose(m *EmptyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *resourceUsageAgentReportCPUTimeServer) Recv() (*CPUTimeRecord, error) {
	m := new(CPUTimeRecord)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ResourceUsageAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource_usage_agent.ResourceUsageAgent",
	HandlerType: (*ResourceUsageAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportCPUTime",
			Handler:       _ResourceUsageAgent_ReportCPUTime_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "resource_usage_agent.proto",
}

func (m *CPUTimeRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CPUTimeRecord) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ResourceGroupTag) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintResourceUsageAgent(dAtA, i, uint64(len(m.ResourceGroupTag)))
		i += copy(dAtA[i:], m.ResourceGroupTag)
	}
	if len(m.RecordListTimestampSec) > 0 {
		dAtA2 := make([]byte, len(m.RecordListTimestampSec)*10)
		var j1 int
		for _, num := range m.RecordListTimestampSec {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintResourceUsageAgent(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.RecordListCpuTimeMs) > 0 {
		dAtA4 := make([]byte, len(m.RecordListCpuTimeMs)*10)
		var j3 int
		for _, num := range m.RecordListCpuTimeMs {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintResourceUsageAgent(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.RecordListScanRows) > 0 {
		dAtA6 := make([]byte, len(m.RecordListScanRows)*10)
		var j5 int
		for _, num := range m.RecordListScanRows {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		dAtA[i] = 0x22
		i++
		i = encodeVarintResourceUsageAgent(dAtA, i, uint64(j5))
		i += copy(dAtA[i:], dAtA6[:j5])
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EmptyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintResourceUsageAgent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CPUTimeRecord) Size() (n int) {
	var l int
	_ = l
	l = len(m.ResourceGroupTag)
	if l > 0 {
		n += 1 + l + sovResourceUsageAgent(uint64(l))
	}
	if len(m.RecordListTimestampSec) > 0 {
		l = 0
		for _, e := range m.RecordListTimestampSec {
			l += sovResourceUsageAgent(uint64(e))
		}
		n += 1 + sovResourceUsageAgent(uint64(l)) + l
	}
	if len(m.RecordListCpuTimeMs) > 0 {
		l = 0
		for _, e := range m.RecordListCpuTimeMs {
			l += sovResourceUsageAgent(uint64(e))
		}
		n += 1 + sovResourceUsageAgent(uint64(l)) + l
	}
	if len(m.RecordListScanRows) > 0 {
		l = 0
		for _, e := range m.RecordListScanRows {
			l += sovResourceUsageAgent(uint64(e))
		}
		n += 1 + sovResourceUsageAgent(uint64(l)) + l
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EmptyResponse) Size() (n int) {
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovResourceUsageAgent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozResourceUsageAgent(x uint64) (n int) {
	return sovResourceUsageAgent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CPUTimeRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResourceUsageAgent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CPUTimeRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CPUTimeRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceGroupTag", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResourceUsageAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthResourceUsageAgent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceGroupTag = append(m.ResourceGroupTag[:0], dAtA[iNdEx:postIndex]...)
			if m.ResourceGroupTag == nil {
				m.ResourceGroupTag = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RecordListTimestampSec = append(m.RecordListTimestampSec, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthResourceUsageAgent
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowResourceUsageAgent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RecordListTimestampSec = append(m.RecordListTimestampSec, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordListTimestampSec", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RecordListCpuTimeMs = append(m.RecordListCpuTimeMs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthResourceUsageAgent
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowResourceUsageAgent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RecordListCpuTimeMs = append(m.RecordListCpuTimeMs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordListCpuTimeMs", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RecordListScanRows = append(m.RecordListScanRows, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthResourceUsageAgent
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowResourceUsageAgent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RecordListScanRows = append(m.RecordListScanRows, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordListScanRows", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipResourceUsageAgent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthResourceUsageAgent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResourceUsageAgent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipResourceUsageAgent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthResourceUsageAgent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResourceUsageAgent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResourceUsageAgent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceUsageAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResourceUsageAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthResourceUsageAgent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowResourceUsageAgent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipResourceUsageAgent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthResourceUsageAgent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResourceUsageAgent   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("resource_usage_agent.proto", fileDescriptor_resource_usage_agent_9193562f1798a3b8)
}

var fileDescriptor_resource_usage_agent_9193562f1798a3b8 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0x2b, 0x31,
	0x14, 0xc6, 0x9b, 0xdb, 0x72, 0xb9, 0x84, 0x3b, 0xb4, 0xe4, 0xf6, 0xea, 0x38, 0x8b, 0xa1, 0x54,
	0x90, 0x59, 0xc8, 0x88, 0x7f, 0x36, 0x2e, 0xb5, 0x88, 0x1b, 0x05, 0x49, 0xdb, 0xa5, 0x84, 0x18,
	0x43, 0x18, 0xea, 0x4c, 0x42, 0x4e, 0xa6, 0xc5, 0x37, 0xf1, 0x11, 0x7c, 0x14, 0x97, 0x2e, 0x5d,
	0x6a, 0x7d, 0x11, 0x99, 0xb4, 0xb5, 0x2d, 0xd4, 0xd5, 0x1c, 0xe6, 0xfb, 0x7e, 0x39, 0xe4, 0x17,
	0x1c, 0x59, 0x09, 0xba, 0xb4, 0x42, 0xb2, 0x12, 0xb8, 0x92, 0x8c, 0x2b, 0x59, 0xb8, 0xd4, 0x58,
	0xed, 0x34, 0x69, 0x6f, 0xca, 0xa2, 0xb6, 0xd2, 0x4a, 0xfb, 0xc2, 0x41, 0x35, 0xcd, 0xba, 0x51,
	0xd3, 0x96, 0xe0, 0xfc, 0x38, 0xfb, 0xd1, 0xfd, 0x40, 0x38, 0xe8, 0xdd, 0x0c, 0x07, 0x59, 0x2e,
	0xa9, 0x14, 0xda, 0xde, 0x93, 0x7d, 0x4c, 0xbe, 0x0f, 0x54, 0x56, 0x97, 0x86, 0x39, 0xae, 0x42,
	0xd4, 0x41, 0xc9, 0x5f, 0xda, 0x5a, 0x24, 0x97, 0x55, 0x30, 0xe0, 0x8a, 0x9c, 0xe2, 0x1d, 0xeb,
	0x39, 0xf6, 0x90, 0x81, 0x63, 0x2e, 0xcb, 0x25, 0x38, 0x9e, 0x1b, 0x06, 0x52, 0x84, 0xbf, 0x3a,
	0xf5, 0xa4, 0x41, 0xb7, 0x66, 0x85, 0xab, 0x0c, 0xdc, 0x60, 0x11, 0xf7, 0xa5, 0x20, 0x27, 0x78,
	0x7b, 0x15, 0x15, 0xa6, 0xf4, 0x38, 0xcb, 0x21, 0xac, 0x77, 0xea, 0x49, 0x40, 0xff, 0x2d, 0xc1,
	0x9e, 0x29, 0x2b, 0xf6, 0x1a, 0xc8, 0x21, 0xfe, 0xbf, 0x4a, 0x81, 0xe0, 0x05, 0xb3, 0x7a, 0x02,
	0x61, 0xc3, 0x2f, 0x23, 0x4b, 0xa6, 0x2f, 0x78, 0x41, 0xf5, 0x04, 0xba, 0x4d, 0x1c, 0x5c, 0xe4,
	0xc6, 0x3d, 0x52, 0x09, 0x46, 0x17, 0x20, 0x8f, 0x00, 0x13, 0x3a, 0xbf, 0xc8, 0xb0, 0x52, 0x76,
	0x56, 0x19, 0x23, 0xb7, 0x38, 0xa0, 0xd2, 0x68, 0xeb, 0xe6, 0x3e, 0xc8, 0x6e, 0xba, 0xd1, 0xfa,
	0x9a, 0xae, 0xe8, 0x87, 0xd2, 0xda, 0xc2, 0x6e, 0x2d, 0x41, 0xe7, 0x7b, 0x6f, 0xcf, 0x7f, 0xd0,
	0xcb, 0x34, 0x46, 0xaf, 0xd3, 0x18, 0xbd, 0x4f, 0x63, 0xf4, 0xf4, 0x19, 0xd7, 0x70, 0x4b, 0x5b,
	0x95, 0xba, 0x6c, 0x34, 0x4e, 0x47, 0x63, 0xff, 0x22, 0x77, 0xbf, 0xfd, 0xe7, 0xf8, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0xf6, 0xe5, 0x31, 0xf3, 0x01, 0x00, 0x00,
}
